# Generated by Django 3.2.10 on 2024-05-19 09:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtraining',
            name='main_training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backed.maintraining'),
        ),
        migrations.AlterField(
            model_name='subtraining',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subtraining',
            name='validity_period',
            field=models.DurationField(choices=[(datetime.timedelta(days=182), '6 months'), (datetime.timedelta(days=365), '1 year'), (datetime.timedelta(days=730), '2 years'), (datetime.timedelta(days=1095), '3 years'), (None, 'Permanent')]),
        ),
    ]
