# Generated by Django 3.2.10 on 2024-05-19 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backed', '0002_auto_20240519_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtraining',
            name='validity_period',
            field=models.DurationField(blank=True, choices=[(datetime.timedelta(days=182), '6 months'), (datetime.timedelta(days=365), '1 year'), (datetime.timedelta(days=730), '2 years'), (datetime.timedelta(days=1095), '3 years'), (None, 'Permanent')], null=True),
        ),
    ]
