# Generated by Django 3.2.10 on 2024-05-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backed', '0004_employee_on_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rig_or_rigless',
            field=models.CharField(choices=[('Rig', 'Rig'), ('Rigless', 'Rigless')], max_length=50),
        ),
    ]
