# Generated by Django 3.2.10 on 2024-05-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backed', '0005_auto_20240520_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gate_pass_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
