# Generated by Django 3.2.10 on 2024-05-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backed', '0009_alter_employeesubtraining_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesubtraining',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='employee_sub_training_pdfs/'),
        ),
    ]
