# Generated by Django 3.2.10 on 2024-05-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backed', '0011_alter_subtraining_validity_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesubtraining',
            name='verify_pdf',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
